name = "MutableShiftedArrays"
uuid = "d3d30c82-a38e-471c-a45a-3d24d2f4d22d"
authors = ["RainerHeintzmann <heintzmann@gmail.com>"]
version = "0.1.0"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[extensions]
CUDASupportExt = ["CUDA", "Adapt"]

[compat]
CUDA = "5.2, 5.3, 5.4, 5.5, 5.6"
Adapt = "3.7, 4.0, 4.1"
julia = "1.9, 1.10, 1.11"

[extras]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "AbstractFFTs"]
